image: gitpod/workspace-yugabytedb

tasks:
  - name: 1a-install-jvm
    init: |
      echo y | sdk install java 17.0.6-librca || true
      gp sync-done jvm-17
  - name: 2a-spring-boot
    env:
      SPRING_PROFILES_ACTIVE: tcysql
    init: | 
      gp sync-await jvm-17
      gradle assemble
    command: |
      gradle test
