spring:
  flyway:
    clean-disabled: false
  jpa:
    show-sql: true
  datasource:
    url: jdbc:yugabytedb://127.0.0.2:5433/yugabyte
    username: yugabyte
    password: yugabyte
    driver-class-name: com.yugabyte.Driver
    hikari:
#      data-source-properties:
#        load-balance: true
#        sslMode: require

